### PR TITLE
docs: Readme file image isn't visible  issue sovled

### PR DESCRIPTION
**Pull request by AnshuPathak-88825**

### CODE REVIEW

**Comment by AnshuPathak-88825** [comment]
PR for issue #44

**Comment by pratap360** [comment]
also add your github profile to about us | contributors page for more info read the contribution.md file

**Comment by AnshuPathak-88825** [comment]
@pratap360 image will update when pr got merged so when this pr got merged then image will be change and my profile will be added

**Comment by pratap360** [comment]
Yea but there is a page named called about so add you profile over there

**Comment by AnshuPathak-88825** [comment]
ok

**Pull request merged**
