### PR TITLE
Improved the designing of cards

### PR DESCRIPTION
**Pull request by zugzwang03**
resolved issue #37 

Screenshots:

bax

### CODE REVIEW

**Comment by zugzwang03** [comment]
https://user-images.githubusercontent.com/95460021/198514578-459ef0e6-62fa-4d4d-b8e6-53d4e489744d.mp4

**Comment by pratap360** [comment]
That's awesome

**Comment by zugzwang03** [comment]
> That's awesome

Thanks 😄

**Comment by pratap360** [comment]
Also add your GitHub profile in about us | contributors and for the more info must check the contibute.md file

**Comment by zugzwang03** [comment]
done :)

**Comment by zugzwang03** [comment]
conflicts resolved :)

**Comment by pratap360** [comment]
thanks 👍 @zugzwang03

**Pull request merged**
